name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: eludris
          path: ./build/app/outputs/flutter-apk/app-release.apk
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Packages
        run: flutter pub get

      - name: Build Windows Files
        run: flutter build windows

      - name: Upload Windows Files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: eludris
          path: ./build/windows/runner/Release/
