name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Cache Flutter Dependencies
        id: cache-flutter-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}-pub-cache

      - name: Install Packages
        if: steps.cache-flutter-dependencies.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Run flutter format
        run: flutter format --set-exit-if-changed .

      - name: Run flutter analyze
        run: flutter analyze
